services:
  web:
    build: .
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - PORT
      - MONGODB_URI
      - CLOUDINARY_API_KEY
      - CLOUDINARY_SECRET_KEY
      - CLOUDINARY_NAME
      - JWT_SECRET
    command: npm run dev