# Variables
@baseUrl = http://localhost:3333/api

###
# Health check
# @name healthCheck
GET {{baseUrl}}/health

###
# @name login
POST {{baseUrl}}/user/login
Content-Type: application/json

{
  "email": "email@teste.com",
  "password": "senhaTeste"
}

###
# @name adminLogin
POST {{baseUrl}}/user/admin
Content-Type: application/json

{
  "email": "email@teste.com",
  "password": "senhaTeste"
}

###
# @name register
POST {{baseUrl}}/user/register
Content-Type: application/json

{
  "name": "Teste",
  "email": "email@teste.com",
  "password": "senhaTeste"
}

